### ISSUE TITLE
Tooltip - Option to remove spacer

### ISSUE THREAD

**Issue by behub** [Necroskillz/StatWeightScore#18]
![image](https://cloud.githubusercontent.com/assets/870239/5656836/14f48e54-9737-11e4-86dd-20202b706fd4.png)

Can there be an option to remove the spacer between the 2 specs?

I'm like a neat freak.

**Comment by Necroskillz** [comment]
I thought about this, and there are a lot of cases where this wouldn't be desirable. I thought about making a compact mode, where only the score would be displayed (not gems, procs etc), but even then there are Offhand scores and there may be other stuff in the future that makes sense for people to see. Overall it would be kind of confusing. Closing this.
