### ISSUE TITLE
AMR Export Weight Changes

### ISSUE THREAD

**Issue by behub** [Necroskillz/StatWeightScore#34]
AMR has added new lines of text to it's export string which is causing errors trying to import it.

An example:
```
set 17 2                  high
set 17 4                  high
set 18 -1                 auto
set 18 2                  auto
set 18 4                  auto
```

I know it's easy to remove those lines pre-import but i would be good to just have SWS ignore them.

**Comment by Necroskillz** [comment]
fixed in 1.9.2
