### ISSUE TITLE
Show valor upgrades on non-empowered baleful items?

### ISSUE THREAD

**Issue by keryja** [Necroskillz/StatWeightScore#35]
Is it possible to also show the valor upgrades (on top of empowered) in the tooltip of non-empowered Baleful items?

**Comment by Necroskillz** [comment]
I don't think so. If it doesn't have Upgrade x/2, it's not possible to tell if it will be upgradable in the future.

**Comment by keryja** [comment]
It does have Upgrade x/2 in the tooltip.

![Item Tooltip](https://cloud.githubusercontent.com/assets/16323751/11870196/c4d0aabe-a4c5-11e5-8763-e00f30c71b4b.png)

Thing is that it's ambiguous, as you could have normal/epic/empowered+upgrade, but forcing it to only show for empowered+upgrade could work.

**Comment by Necroskillz** [comment]
I'll see what I can do.
