### ISSUE TITLE
An error occured in loot list on Encounter Journal

### ISSUE THREAD

**Issue by WetU** [Necroskillz/StatWeightScore#37]
1x StatWeightScore\ItemLink.lua:100: bad argument #4 to 'format' (string expected, got table)
[C]: in function `format'
StatWeightScore\ItemLink.lua:100: in function `ToString'
StatWeightScore\Item.lua:383: in function `ConvertTierToken'
StatWeightScore\Tooltip.lua:233: in function `AddToTooltip'
StatWeightScore\Tooltip.lua:86: in function <StatWeightScore\Tooltip.lua:85>
[C]: ?
[C]: ?
Archy\Libs\AceHook-3.0\AceHook-3.0-8.lua:95: in function <Archy\Libs\AceHook-3.0\AceHook-3.0.lua:87>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetHyperlink'
...zzard_EncounterJournal\Blizzard_EncounterJournal-1.0.lua:1578: in function `EncounterJournal_SetTooltip'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = "%s|H%s:%s:%s:%s:%s:%s:%s:%s:%s:%s:%s:%s:%s"
(*temporary) = "|cff20ff20"
(*temporary) = "item"
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = <table> {
}
(*temporary) = "string expected, got table"

**Comment by Necroskillz** [comment]
which item? whats your weights?

**Comment by WetU** [comment]
This error seemes to occur when first mouse hover on tier token

Item ID 119306
