### ISSUE TITLE
Error with version 7.2.0

### ISSUE THREAD

**Issue by cexikitin** [Necroskillz/StatWeightScore#39]
2x AceLocale-3.0-6: StatWeightScore: Missing entry for 'Matcher_Precheck_BonusArmor'
StatWeightScore\Score.lua:26: in function <StatWeightScore\Score.lua:12>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-12.lua:529: in function `InitializeAddon'
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-12.lua:644: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals:
nil

**Comment by Necroskillz** [comment]
already fixed in 7.2.1
