### ISSUE TITLE
An error occured after 7.2 patch

### ISSUE THREAD

**Issue by WetU** [Necroskillz/StatWeightScore#43]
77x Usage: local name, iconFileID, setID, isEquipped, numItems, numEquipped, numInInventory, numLost, numIgnored = C_EquipmentSet.GetEquipmentSetInfo(equipmentSetID)
[C]: in function `GetEquipmentSetInfo'
...faceBlizzard_Deprecated\Deprecated_7_2_0.lua:116: in function `GetEquipmentSetInfoByName'
StatWeightScore\Tooltip.lua:135: in function <StatWeightScore\Tooltip.lua:114>
StatWeightScore\Tooltip.lua:269: in function `AddToTooltip'
StatWeightScore\Tooltip.lua:86: in function <StatWeightScore\Tooltip.lua:85>
[C]: ?
[C]: in function `SetQuestLogItem'
FrameXML\GameTooltip.lua:531: in function <FrameXML\GameTooltip.lua:524>
[C]: in function `EmbeddedItemTooltip_SetItemByQuestReward'
FrameXML\GameTooltip.lua:125: in function `GameTooltip_AddQuestRewardsToTooltipWithHeader'
FrameXML\GameTooltip.lua:74: in function `GameTooltip_AddQuestRewardsToTooltip'
FrameXML\WorldMapFrame.lua:2002: in function <FrameXML\WorldMapFrame.lua:1953>
[C]: in function `TaskPOI_OnEnter'
...rfaceWorldQuestTracker\WorldQuestTracker.lua:1122: in function <...rfaceWorldQuestTracker\WorldQuestTracker.lua:1118>

Locals:
(*temporary) = "Usage: local name, iconFileID, setID, isEquipped, numItems, numEquipped, numInInventory, numLost, numIgnored = C_EquipmentSet.GetEquipmentSetInfo(equipmentSetID)"

SWS broken on 7.2 client

**Comment by WetU** [comment]
Check Pull requests

**Comment by Necroskillz** [comment]
thx, i will merge it over the weekend.
